import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import './globals.css';
import ReduxProvider from '@/providers/ReduxProvider';
import { SettingsModalProvider } from '@/context/SettingsModalContext';
import ClientModalWrapper from '@/context/ClientModalWrapper';


const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const inter = Inter({ variable: '--font-inter', subsets: ['latin'] });
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Chattersticks',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${inter.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <SettingsModalProvider>
            {children}
            <ClientModalWrapper />
          </SettingsModalProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
